window.FALLBACK_TICKETS = [
  {
    id: 1,
    name: 'Child Pass',
    category: 'child',
    price: 150,
    original_price: 200,
    description: 'Perfect for little ones below 10 years.',
    features: ['Kids Splash Zone', 'Mini Water Slides', 'Banana Ride', 'Rain Dance', 'Tub Ride'],
    color: '#22c55e',
    badge: null,
  },
  {
    id: 2,
    name: 'Adult Pass',
    category: 'adult',
    price: 250,
    original_price: 350,
    description: 'Full access to all major rides and water attractions.',
    features: ['All 20+ Rides', 'Wave Pool', 'Giant Slides', 'Rain Dance', 'Wall Climbing', 'Lazy River'],
    color: '#00d4ff',
    badge: 'Most Popular',
  },
  {
    id: 3,
    name: 'Premium Pass',
    category: 'premium',
    price: 390,
    original_price: 500,
    description: 'Priority access with added comfort and premium perks.',
    features: ['Everything in Adult Pass', 'Priority Queue', 'Locker Room', 'Changing Room', 'Free Parking'],
    color: '#ffd166',
    badge: 'Best Value',
  },
  {
    id: 4,
    name: 'Couple Pass',
    category: 'couple',
    price: 450,
    original_price: 600,
    description: 'A special package for two adults visiting together.',
    features: ['2 Adult Entries', 'Major Ride Access', 'Wave Pool', 'Rain Dance', 'Priority Entry'],
    color: '#f472b6',
    badge: 'Couple Deal',
  },
];
